sh_ffj0_system_identification_controller:
  joint: FFJ0
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_ffj3_system_identification_controller:
  joint: FFJ3
  position_pid:
    d: 0.0
    i: -1.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_ffj4_system_identification_controller:
  joint: FFJ4
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_lfj0_system_identification_controller:
  joint: LFJ0
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_lfj3_system_identification_controller:
  joint: LFJ3
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_lfj4_system_identification_controller:
  joint: LFJ4
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_lfj5_system_identification_controller:
  joint: LFJ5
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_mfj0_system_identification_controller:
  joint: MFJ0
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_mfj3_system_identification_controller:
  joint: MFJ3
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_mfj4_system_identification_controller:
  joint: MFJ4
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_rfj0_system_identification_controller:
  joint: RFJ0
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_rfj3_system_identification_controller:
  joint: RFJ3
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_rfj4_system_identification_controller:
  joint: RFJ4
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_thj1_system_identification_controller:
  joint: THJ1
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_thj2_system_identification_controller:
  joint: THJ2
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_thj3_system_identification_controller:
  joint: THJ3
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_thj4_system_identification_controller:
  joint: THJ4
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_thj5_system_identification_controller:
  joint: THJ5
  position_pid:
    d: 0.0
    i: 0.0
    i_clamp: 0.1
    max_velocity: 1.5
    min_velocity: -1.5
    p: -3.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_wrj1_system_identification_controller:
  joint: WRJ1
  position_pid:
    d: 0.0
    i: -0.1
    i_clamp: 0.1
    max_velocity: 0.5
    min_velocity: -0.5
    p: -2.0
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0

sh_wrj2_system_identification_controller:
  joint: WRJ2
  position_pid:
    d: 0.0
    i: -0.1
    i_clamp: 0.1
    max_velocity: 0.5
    min_velocity: -0.5
    p: -2.3
    position_deadband: 0.0
  type: tracking_controllers/SrhSystemIdentificationController
  velocity_pid:
    d: 0.0
    friction_deadband: 100.0
    i: 0.0
    i_clamp: 0.0
    max_force: 20.0
    p: -20.0


