sh_ffj0_inverse_dynamics_controller:
  joint: FFJ0
  model: 
    order: 2
    param: [0.0, 1.0,-0.000001,-20.5091, 0.0, 0.4059, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_ffj3_inverse_dynamics_controller:
  joint: FFJ3
  model: 
    order: 2
    param: [0.0, 1.0, -0.0009, -45.1068, 0.0, 0.8890, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_ffj4_inverse_dynamics_controller:
  joint: FFJ4
  model: 
    order: 2
    param: [0.0, 1.0, -0.000024651, -1247.5, 0.0, 24.6509, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController
     
sh_mfj0_inverse_dynamics_controller:
  joint: MFJ0
  model: 
    order: 2
    param: [0.0, 1.0,-0.000001,-20.5091, 0.0, 0.4059, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_mfj3_inverse_dynamics_controller:
  joint: MFJ3
  model: 
    order: 2
    param: [0.0, 1.0, -0.0000043534,-219.5875 , 0.0, 4.3534, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_mfj4_inverse_dynamics_controller:
  joint: MFJ4
  model: 
    order: 2
    param: [0.0, 1.0, -0.000024651, -1247.5, 0.0, 24.6509, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj0_inverse_dynamics_controller:
  joint: RFJ0
  model: 
    order: 2
    param: [0.0, 1.0,-0.000001,-20.5091, 0.0, 0.4059, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj3_inverse_dynamics_controller:
  joint: RFJ3
  model: 
    order: 2
    param: [0.0, 1.0, -0.0000043534,-219.5875 , 0.0, 4.3534, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj4_inverse_dynamics_controller:
  joint: RFJ4
  model: 
    order: 2
    param: [0.0, 1.0, -0.000024651, -1247.5, 0.0, 24.6509, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj0_inverse_dynamics_controller:
  joint: LFJ0
  model: 
    order: 2
    param: [0.0, 1.0,-0.000001,-20.5091, 0.0, 0.4059, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj3_inverse_dynamics_controller:
  joint: LFJ3
  model: 
    order: 2
    param: [0.0, 1.0, -0.0000043534,-219.5875 , 0.0, 4.3534, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj4_inverse_dynamics_controller:
  joint: LFJ4
  model: 
    order: 2
    param: [0.0, 1.0, -0.000024651, -1247.5, 0.0, 24.6509, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj5_inverse_dynamics_controller:
  joint: LFJ5
  model: 
    order: 2
    param: [0.0, 1.0, -0.0018, -92.3272, 0.0, 1.8322, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj1_inverse_dynamics_controller:
  joint: THJ1
  model: 
    order: 2
    param: [0.0, 1.0, -1.0, -503.0506, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj2_inverse_dynamics_controller:
  joint: THJ2
  model: 
    order: 2
    param: [0.0, 1.0, -0.01, -506.0481, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj3_inverse_dynamics_controller:
  joint: THJ3
  model: 
    order: 2
    param: [0.0, 1.0, -0.01, -504.7123, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj4_inverse_dynamics_controller:
  joint: THJ4
  model: 
    order: 2
    param: [0.0, 1.0, -0.01, -503.3904, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj5_inverse_dynamics_controller:
  joint: THJ5
  model: 
    order: 2
    param: [0.0, 1.0, -0.0065, -330.6496, 0.0, 6.5457, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_wrj1_inverse_dynamics_controller:
  joint: WRJ1
  model: 
    order: 2
    param: [0.0, 1.0, -0.01, -940.5380, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_wrj2_inverse_dynamics_controller:
  joint: WRJ2
  model: 
    order: 2
    param: [0.0, 1.0, -0.01, -1031.0, 0.0, 10.0, 1.0, 0.0, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

  




