sh_ffj0_inverse_dynamics_controller:
  joint: FFJ0
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]   
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_ffj3_inverse_dynamics_controller:
  joint: FFJ3
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_ffj4_inverse_dynamics_controller:
  joint: FFJ4
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]  
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController
     
sh_mfj0_inverse_dynamics_controller:
  joint: MFJ0
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_mfj3_inverse_dynamics_controller:
  joint: MFJ3
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]   
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_mfj4_inverse_dynamics_controller:
  joint: MFJ4
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj0_inverse_dynamics_controller:
  joint: RFJ0
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]    
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj3_inverse_dynamics_controller:
  joint: RFJ3
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]    
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_rfj4_inverse_dynamics_controller:
  joint: RFJ4
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj0_inverse_dynamics_controller:
  joint: LFJ0
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj3_inverse_dynamics_controller:
  joint: LFJ3
  model_param: [0.001, 61.3451, 0.701, 138.6009, 3.8127, 0.8693, 7.8032, 1.9592, 0.0]    
  pos_filter_window: 5  
  vel_filter_window: 10  
  motor_min_force_threshold: 20
  pid:
    p: -25
    i: -1.0
    d: -9.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 1000.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj4_inverse_dynamics_controller:
  joint: LFJ4
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_lfj5_inverse_dynamics_controller:
  joint: LFJ5
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]    
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj1_inverse_dynamics_controller:
  joint: THJ1
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj2_inverse_dynamics_controller:
  joint: THJ2
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj3_inverse_dynamics_controller:
  joint: THJ3
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]     
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj4_inverse_dynamics_controller:
  joint: THJ4
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]       
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_thj5_inverse_dynamics_controller:
  joint: THJ5
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_wrj1_inverse_dynamics_controller:
  joint: WRJ1
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

sh_wrj2_inverse_dynamics_controller:
  joint: WRJ2
  model_param: [0.00001, 35.8419, 1.0127, 2.8664, 0.0006, 2.0714, 2.8375, 8.8603, 0.0]      
  pos_filter_window: 5  
  vel_filter_window: 50  
  pid:
    p: -625
    i: -1.0
    d: -45.0
    i_clamp: 0.1
    deadband: 0.0
    friction_deadband: 0.0
    max_force: 50.0
  type: tracking_controllers/SrhInverseDynamicsController

  




