max_force: 2
sensor_topics:  [/sr_tactile/touch/ff,
                 /sr_tactile/touch/lf,
                 /sr_tactile/touch/mf,
                 /sr_tactile/touch/rf,
                 /sr_tactile/touch/th]


