max_force: 2
sensor_topics:  [/ffdistal/ContactState,
                 /mfdistal/ContactState,
                 /rfdistal/ContactState,
                 /lfdistal/ContactState,
                 /thdistal/ContactState]


